// /** @format */

// export default {
//     RestaurantName : 'Gamigedara Restaurant',
//     RestaurantAddress : 'no.50 Kurunegala-Narammala-Madampe Rd, Kurunegala 60000',

//     // Common words
//     Ok : 'Ok',
//     Cancel : 'Cancel',
//     FirstName : 'First Name',
//     LastName : 'Last Name',
//     MobileNumber : 'Mobile Number',
//     Email : 'Email',
//     Update : 'Update',
//     Password : 'Password',
//     ConfirmPassword : 'Confirm Password',
//     Success : 'Success',
//     Continue : 'Continue',
//     PleaseWait : 'Please Wait',
//     Error : 'Error',
//     Alert :'Alert',
//     Yes : 'Yes',
//     No : 'No',
//     AreYouSure : 'Are You Sure',
//     Settings : 'Settings',
//     Hi : 'Hi',
//     Rs : 'Rs.',
//     LoadingPleaseWait : 'Loading Please wait...',
//     Change : 'Change',
//     Skip : 'Skip »',
//     Search : 'Search', 
//     SearchHere : 'Search Here...',
//     Open : 'Open',
//     Close : 'Close',
//     Now : 'Now',

//     // Alert messages
//     SomethingWentWrong : 'Something went wrong, please try again',
//     NoUserFound : 'No user found with this email, to continue create new account with this email or re-enter login details',
//     Retry : 'Retry',
//     LocationUpdatedSuccessfully : 'Location updated successfully',
//     SomeRequiredFieldsEmpty : 'Some required fields are empty, please check it and try again',
//     NoImageSelected : 'No image selected for upload, please select image and try again.',
//     FoundIncolmpleteSession : 'Found incomplete session with new account creating, Do you want to continue it ?',
//     ContinueAsSelfPickup : 'Continue as Self Pickup user ?',
//     DeliveryUnavailable : 'Our delivery service is unavailable on your location, Click here to change your location',
//     CannotApplySelectedPromoCode : 'Cannot apply promo code you have selected',
//     YouWantToExitApp : 'You want to exit the app ?',
//     DoYouWantToClearCart : 'Do you want to clear cart ?',
//     AppearsOrderNotPlaced : 'It appears that your order has not been placed properly. Try again or contact us',

//     // Notifications 
//     Orderplaced : 'Order Placed',
//     OrderPlacedSuccessfully : 'Your order has been placed successfully',

//     // Login Page
//     loginCardTitle : 'Get Food You Want',
//     loginCardSubtitle : 'Satisfy your cravings by getting the food you love from your favorite restaurant delivered to you fast, Delivery & takeout from the best restaurant.',
//     googlebuttontitle : 'Login With Google',
//     facebookbuttontitle : 'Login With Facebook',
//     phonenumberbuttontitle : 'Login With Phone Number',
//     LoginwithUserNamePassword : 'Login With Username And Password',
//     LoginginPleaseWait : 'Logging in please wait...',

//     // Phone number input
//     EnterPhoneNumber : 'Phone number',
//     PhonenumberInputPlaeholder : 'Eg : 71 234 5678',
//     RegisterButtonTitle : 'Register',

//     //alert
//     NonumberAlert : 'Please enter valid phone number for registration process',
//     CreateNewAccount : 'Create New Account',

//     // Verify OTP
//     Verify : 'Verify',
//     VerifyButtonTitle : 'Continue',
//     OtpPageDescription : 'We texted you a code to verify your phone number ',
//     DidntRecived : `Didn't recieved code?`,
//     SendAgain : 'Send Again',

//     // Username & Password Login Model
//     Login : 'Login',
//     Emailplaceholder : 'Enter your email or username',
//     Password : 'Password',
//     Passwordplaceholder : 'Enter your password',
//     Or : 'Or',
//     ShowHidePassword : 'Show Password',
//     CreateNewAccount : 'Create New Account',
//     ForgetPassword : 'Forget Password',

//     // Location Settings
//     DeliveryOption : 'Delivery Option',
//     SearchLocation : 'Search Location',
//     SearchLocationSubLine : 'Click here to search your address',
//     SelectMyLocationNow : 'Select My Location Now',
//     SelectMyLocationNowSubLine : 'Click here to select your location now',
//     SelfPickup : 'Self Pickup',
//     SelfPickupSubLine : 'Click here to continue anyway',
//     DineIn : 'Dine In',
//     DineInSubLine : 'Click here to dine in',
//     CannotGetYourLocation : 'Faied to get your location, click here to enable location service, Click here to retry or go to location settings',
//     RecentLocations : 'Recent Locations',

//     // Search Address
//     OutOfDeliveryArea : 'Out Of Delivery Area',

//     // Select Now Location
//     ServiceNotAvailableHere : 'Service Not Available Here',
//     ContinueAsSelfPickupUser : 'Continue As Self Pickup User',
//     ApartmentNoHouseNo : 'Apartment No / House No (Optional)',
//     StreetCity : 'Street & City',
//     FetchingYourLocation : 'Fetching Your Location',
//     ApartmentNumber : 'Apartment Number',
//     StreetCity : 'Street & City',

//     // Home 
//     SelfPickupUser : 'SELF PICKUP USER',
//     DeliveringFood : 'DELIVERING FOOD TO',
//     WhatDoYouWantToFind : 'What do you want to find ?',
//     ViewOurMenu : 'View Our Menu',
//     LatestOffer : 'Latest Offer',
//     BestDeals : 'Best Deals, Get In Touch With Us',
//     TopPicks : 'Top Picks',
//     OurRestaurants : 'Our Restaurants',
//     Validtill : 'Valid Till',
//     GoodMorning : 'Good Morning',
//     GoodAfternoon : 'Good Afternoon',
//     GoodEvening : 'Good Evening',

//     //Multi Restaurant Home
//     BestOffers : 'Best Offers',
//     RestaurantsNearYou : 'Restaurants Near You',
//     GroceriesNearYou : 'Groceries Near You',
//     FeaturedClothingOutletsNearYou : 'Featured Clothing Outlets Near You',
//     WhatWouldYouLike : 'What would you like to eat today ?',
//     ViewAll : 'View All',
//     NoRestaurants : 'No Restaurants Near You',
//     NoGroceries : 'No Groceries Near You',
//     NoFeaturedOutlets : 'No Clothing Outlets Near You', 
//     YouHaveOngoing : 'You have ongoing order',
//     ValidFrom : 'Valid From',
//     ValidTo : 'Valid to',
//     To : 'To',

//     // Food Item Page,
//     PreparationNote : 'Preparation Note',
//     Portions : 'Portions',
//     Addons : 'Add-Ons',
//     AddToCart : 'Add to cart',
//     Select : 'Select',

//     // Menu List 
//     ItemsinCart : 'Items In Cart',
//     ItemNotAvailableUntilTomorrow : 'Item not available untill tomorrow',
//     ItemNotAvailable : 'Currently not available',

//     // Cart Page
//     DeliveryAddress : 'Delivery Address',
//     DeliveryContact : 'Delivery Contact',
//     ArrivalTime : 'Arrival Time',
//     CartItems : 'Cart Items',
//     ClearCart : 'Clear Cart',
//     ClickToAddPromoCode : 'Click to add Promo Code',
//     ClickToChangePromoCode : 'Click to change / remove Promo Code',
//     AddDeliveryNote : 'Add Delivery Note',
//     SubTotal : 'Sub Total',
//     ServiceCharge : 'Service Charge',
//     Promotion : 'Promotion',
//     Total : 'Total',
//     PlaceOrder : 'Place Order',
//     DeliveryCharge : 'Delivery Charge',
//     SelectedRestaurent : 'Selected Restaurent',
//     SelectShedule : 'Select Shedule',
//     Delivery : 'Delivery',
//     CalculatingTotal : 'Calculating Total',
//     DeliveryName : 'Delivery Name',
//     DeliveryNamePlaceholder : 'Eg : John Smith', 
//     YouAreOutFromDeliveryRange : 'Your location is out from delivery range, please change your delivery location for order items',
//     ChangeLocation : 'Change My Address',
//     CallUs : 'Contact our support',
//     SelectRestaurent : 'Select Restaurant',
//     SetShedule : 'Set Shedule Date and Time',
//     Save : 'Save',
//     Date : 'Date',
//     Time : 'Time',
//     AddAddress : 'Add Address',
//     AddressLine1 : 'Address line 1',
//     AddressLine2 : 'Address Line 2',
//     ClickHereToAddDelivery : 'Click here to add delivery info',
//     DeliveryInfo : 'Delivery Info',
//     PleaseAddDeliveryInfo : 'Please add delivey info for place order',
//     CartTotal : 'Cart total',
//     Discount : 'Discount',
//     DeliveryFee : 'Delivery fee',
//     TotalAmount : 'Total amount',
//     PaymentSummery : 'Payment Summery',
//     PayWith : 'Pay With',

//     // Promotion Screen
//     Apply : 'Apply',
//     Remove : 'Remove',
//     YouHaveAlreadyApplied : 'You have already applied promotion code, do you want to remove it and apply this promo code ?',
//     RemoveIt : 'Remove',

//     // Account Page
//     Account : 'Account',
//     MyProfile : 'My Profile',
//     Address : 'Address',
//     Orders : 'Orders',
//     RateUs : 'Rate Us',
//     LogOut : 'Log Out',
//     YouWantToLogout : 'You want to Log Out ?',
//     PrivacyPolicy : 'Privacy Policy',

//     // Update Profile
//     SelectCity : 'Select City',
//     City : 'City',

//     // Order Rate Page
//     HowWasYourOrder : 'How Was Your Order',
//     HowWasYourDriver : 'How Was Your Driver',
//     RateNow : 'Rate Now',
//     RateOrder : 'Rate Order',

//     // Order Status Page
//     EstTime : 'Estimated Arrival',
//     OrderPending : 'Your Order Is Pending...',
//     OrderConfirmed : 'Your Order Is Confirmed',
//     OrderPreparing : 'Your Order Is Preparing',
//     OrderPrepared : 'Your Order Prepared',
//     OrderPickedByDriver : 'Your Order Is Picked By Driver',
//     OrderDelivered : 'Your Order Delivered',
//     UndefinedOrderStatus : 'Undefined Order Status',
//     EstimatedDeliveryTime : 'est delivery time',
//     // ---------- Bottom Drawer ----------//
//     YourDriver : 'Your Driver : ',
//     DeliveryTime : 'Delivery Time : ',
//     PaymentMethod : 'Payment Method',
//     Cash : 'Cash',

//     //Restaurant List 
//     Est : 'Est.',
//     Mins : 'mins',
//     Eats : 'Eats',
//     Grocery : 'Grocery',
//     Fashion : 'Fashion',
//     Doyouwantclearcart : 'Do you want to clear cart or save it for later',
//     StartNewOrder : 'Srart New Order',
//     Clear : 'Clear',
//     UnableToFindStoresNearYou : 'Unable to find stores near you',

//     //Orders Page
//     YouHaveNOrders : 'You Have No Orders',
//     YouHaveNoSavedCart : 'You Have No Saved Cart',
//     View : 'View',
//     Track : 'Track',
//     OrderId : 'Order Id',
//     OrderDate : 'Order Date',
//     OrderStatus : 'Order Status',
//     Cart : 'Cart',
//     Clearsavedcart : 'Clear saved cart',
//     AddThisItemsToCart : 'Add this items to cart ?',
//     ClearSavedItems : 'Clear saved items ?',

//     //*** Order Steps ***//
//     Pending : 'Pending',
//     Confirmed : 'Confirmed',
//     Preparing : 'Preparing',
//     Prepared : 'Prepared',
//     DriverPicked : 'Driver Picked',
//     Delivered : 'Delivered',

//     // Order View
//     ThanksForOrdering : 'Thanks for ordering, ',
//     HereIsYourRecipt : 'Here is your recipt for order id ',
//     CardPayment : 'Card Payment',
//     CashPayment : 'Cash Payment'
// }

/** @format */

export default {
    RestaurantName : 'Gamigedara Restaurant',
    RestaurantAddress : 'no.50 Kurunegala-Narammala-Madampe Rd, Kurunegala 60000',

    // Common words
    Ok : 'Ok',
    Cancel : 'Cancel',
    FirstName : 'First Name',
    LastName : 'Last Name',
    MobileNumber : 'Mobile Number',
    Email : 'Email',
    Update : 'Update',
    Password : 'Password',
    ConfirmPassword : 'Confirm Password',
    Success : 'Success',
    Continue : 'Continue',
    PleaseWait : 'Please Wait',
    Error : 'Error',
    Alert :'Alert',
    Yes : 'Yes',
    No : 'No',
    AreYouSure : 'Are You Sure',
    Settings : 'Settings',
    Hi : 'Hi',
    Rs : 'Rs.',
    currency : 'Rs.',
    LoadingPleaseWait : 'Loading Please wait...',
    Change : 'Change',
    Skip : 'Skip »',
    Search : 'Search', 
    SearchHere : 'Search Here...',
    Open : 'Open',
    Close : 'Close',
    Now : 'Now',
    OpenUntil : 'Open untill',
    Understood : 'Place another order',
    MerchantIsClosed : 'Merchant is closed',
    MerchantIsBusyNow : 'Merchant is busy now',
    NoDeliveryAvailableInYourMerchant : 'Delivery is unavailable',
    SelfPickupDineInOnly : 'Self pickup / Dinein Only',
    LoginSignIn : 'Login',
    Canceled : 'Canceled',

    // Alert messages
    SomethingWentWrong : 'Something went wrong, please try again',
    NoUserFound : 'No user found with this email, to continue create new account with this email or re-enter login details',
    Retry : 'Retry',
    LocationUpdatedSuccessfully : 'Location updated successfully',
    SomeRequiredFieldsEmpty : 'Some required fields are empty, please check it and try again',
    NoImageSelected : 'No image selected for upload, please select image and try again.',
    FoundIncolmpleteSession : 'Found incomplete session with new account creating, Do you want to continue it ?',
    ContinueAsSelfPickup : 'Continue as Self Pickup user ?',
    DeliveryUnavailable : 'Our delivery service is unavailable on your location, Click here to change your location',
    CannotApplySelectedPromoCode : 'Cannot apply promo code you have selected',
    YouWantToExitApp : 'You want to exit the app ?',
    DoYouWantToClearCart : 'Do you want to clear cart ?',
    AppearsOrderNotPlaced : 'It appears that your order has not been placed properly. Try again or contact us',
    DoYouWantToRemoveThisItem : 'Do you want to remove from cart ?',

    // Notifications 
    Orderplaced : 'Order Placed',
    OrderPlacedSuccessfully : 'Your order has been placed successfully',

    // Login Page
    loginCardTitle : 'Login or create an account',
    loginCardSubtitle : 'Satisfy your cravings by getting the food you love from your favorite restaurant delivered to you fast, Delivery & takeout from the best restaurant.',
    googlebuttontitle : 'Continue with Google',
    facebookbuttontitle : 'Continue with Facebook',
    applebuttontitle : 'Sign In With Apple',
    phonenumberbuttontitle : 'Continue with Phone Number',
    LoginwithUserNamePassword : 'Continue with Email And Password',
    LoginginPleaseWait : 'Logging in please wait...',
    ContinueAsGuest : 'Continue As Guest',

    // Splash
    NoNetworkConnection : 'No network connection',
    LocationServiceDisabled : 'Location service disabled',

    // Phone number input
    EnterPhoneNumber : 'Phone number',
    PhonenumberInputPlaeholder : 'Eg : 71 234 5678',
    RegisterButtonTitle : 'Register',

    //alert
    NonumberAlert : 'Please enter valid phone number for registration process',
    CreateNewAccount : 'Create New Account',

    // Verify OTP
    Verify : 'Verify',
    VerifyButtonTitle : 'Continue',
    OtpPageDescription : 'We texted you a code to verify your phone number ',
    DidntRecived : `Didn't recieved code?`,
    SendAgain : 'Send Again',
    OtpDescription2 : 'OTP will arrive within 60 seconds, please be patience',

    // Username & Password Login Model
    Login : 'Login',
    Emailplaceholder : 'Enter your email',
    Password : 'Password',
    Passwordplaceholder : 'Enter your password',
    Or : 'Or',
    ShowHidePassword : 'Show Password',
    CreateNewAccount : 'Create New Account',
    ForgetPassword : 'Forget Password',
    ResetPassword : 'Reset Password',
    ForgetPasswordPageSubTitle : 'We will sent a password reset email to your mail',

    // Location Settings
    DeliveryOption : 'Delivery Option',
    SearchLocation : 'Search Location',
    SearchLocationSubLine : 'Click here to search your address',
    SelectMyLocationNow : 'Use My Current Location',
    SelectMyLocationNowSubLine : 'Click here to select your location now',
    SelfPickup : 'Self Pickup',
    SelfPickupSubLine : 'Click here to continue anyway',
    DineIn : 'Dine In',
    DineInSubLine : 'Click here to dine in',
    CannotGetYourLocation : 'Faied to get your location, click here to enable location service',
    RecentLocations : 'Recent Locations',

    // Search Address
    OutOfDeliveryArea : 'Out Of Delivery Area',

    // Select Now Location
    ServiceNotAvailableHere : 'Service Not Available Here',
    ContinueAsSelfPickupUser : 'Continue As Self Pickup User',
    ApartmentNoHouseNo : 'Apartment No / House No (Optional)',
    StreetCity : 'Street & City',
    FetchingYourLocation : 'Fetching Your Location',
    ApartmentNumber : 'Apartment Number',
    StreetCity : 'Street & City',

    // Home 
    SelfPickupUser : 'SELF PICKUP USER',
    DeliveringFood : 'DELIVERING TO',
    WhatDoYouWantToFind : 'All in one food ordering platform',
    ViewOurMenu : 'View Our Menu',
    LatestOffer : 'Latest Offer',
    BestDeals : 'Best Deals, Get In Touch With Us',
    TopPicks : 'Top Picks',
    OurRestaurants : 'Our Restaurants',
    Validtill : 'Valid Till',
    GoodMorning : 'Good Morning',
    GoodAfternoon : 'Good Afternoon',
    GoodEvening : 'Good Evening',

    //Multi Restaurant Home
    BestOffers : 'Best Offers',
    RestaurantsNearYou : 'Restaurants Near You',
    GroceriesNearYou : 'Groceries Near You',
    TrendingFashion : 'Trending Fashion',
    WhatWouldYouLike : `Let's try our Menu`,
    ViewAll : 'View All',
    NoRestaurants : 'It seems no restaurants near you',
    NoGroceries : 'It seems no groceries near you',
    NoFeaturedOutlets : 'It Seems No Clothing Outlets Near You', 
    YouHaveOngoing : 'You have ongoing order',
    ValidFrom : 'Valid From',
    ValidTo : 'Valid to',
    To : 'To',
    HeyThere : 'Hey There',
    LoginOrCreateAnAccountForBetter : 'Login or create an account for a better ordering experience.',
    LocationPermissionDenied : 'Location permission denied',

    // Food Item Page,
    PreparationNote : 'Preparation Note',
    Portions : 'Portions',
    Addons : 'Add-Ons',
    Suggetions : 'We Have Suggections',
    SpecialNotes : 'Special Notes',
    AddToCart : 'Add to cart',
    ItemNotAvailable : 'Currently Not Available',
    Select : 'Select',
    Variants : 'Variants',
    About : 'About',

    // Menu List 
    ItemsinCart : 'Items In Cart',
    Info : 'Info',

    // Cart Page
    DeliveryAddress : 'Delivery Address',
    DeliveryContact : 'Delivery Contact',
    ArrivalTime : 'Arrival Time',
    CartItems : 'Cart Items',
    ClearCart : 'Clear Cart',
    ClickToAddPromoCode : 'Click to add Promo Code',
    ClickToChangePromoCode : 'Click to change / remove Promo Code',
    AddDeliveryNote : 'Add Delivery Note',
    SubTotal : 'Sub Total',
    ServiceCharge : 'Service Charge',
    Promotion : 'Promotion',
    Total : 'Total',
    PlaceOrder : 'Place Order',
    DeliveryCharge : 'Delivery Charge',
    SelectedRestaurent : 'Selected Merchant',
    SelectShedule : 'Select Shedule',
    Delivery : 'Delivery',
    CalculatingTotal : 'Calculating Total',
    DeliveryName : 'Receiver Name',
    DeliveryNamePlaceholder : 'Eg : John Smith', 
    YouAreOutFromDeliveryRange : 'Your location is out from delivery range, please change your delivery location for order items',
    ChangeLocation : 'Change My Address',
    CallUs : 'Contact our support',
    SelectRestaurent : 'Select Restaurant',
    SetShedule : 'Set Shedule Date and Time',
    Save : 'Save',
    Date : 'Date',
    Time : 'Time',
    AddAddress : 'Add Address',
    AddressLine1 : 'Address line 1',
    AddressLine2 : 'Address Line 2',
    ClickHereToAddDelivery : 'Click here to add delivery info',
    DeliveryInfo : 'Delivery Info',
    PleaseAddDeliveryInfo : 'Please add delivey info for place order',
    CartTotal : 'Cart total',
    Discount : 'Promo Discount',
    DeliveryFee : 'Delivery fee',
    TotalAmount : 'Total amount',
    PaymentSummery : 'Payment Summery',
    PayWith : 'Pay With',
    YouAreSaving : 'You are saving',
    TooFar : 'It seems your location is too far away from the merchant, Still you can continue with self pickup. ',
    ChangeLocation2 : 'Change location',

    // Promotion Screen
    Apply : 'Apply',
    Remove : 'Remove',
    YouHaveAlreadyApplied : 'You have already applied promotion code, do you want to remove it and apply this promo code ?',
    RemoveIt : 'Remove',

    // Account Page
    Account : 'Account',
    MyProfile : 'My Profile',
    Address : 'Address',
    Orders : 'Orders',
    RateUs : 'Rate Us',
    LogOut : 'Log Out',
    YouWantToLogout : 'You want to Log Out ?',
    PrivacyPolicy : 'Privacy Policy',
    AboutUs : 'About Us',

    // Update Profile
    SelectCity : 'Select City',
    City : 'City',

    // Order Rate Page
    HowWasYourOrder : 'How Was Your Order',
    HowWasYourDriver : 'How Was Your Driver',
    HowWasEachItem : 'How Was Each Item',
    RateNow : 'Rate Now',
    RateOrder : 'Rate Order',
    WriteYourComment : 'Write your review',
    YourSuggections : 'Your suggections are verry important to us please share your experience with us to improve our merchant',

    // Order Status Page
    EstTime : 'Estimated Arrival',
    OrderPending : 'Your Order Is Pending...',
    OrderConfirmed : 'Your Order Is Confirmed',
    OrderPreparing : 'Your Order Is Preparing',
    OrderPrepared : 'Your Order Prepared',
    OrderPickedByDriver : 'Your Order Is Picked By Rider',
    OrderPreparedAtRestaurant : 'Order Is Prepared At Restaurant',
    Collected : 'Order Is Successfully Completed',
    OrderDelivered : 'Your Order Delivered',
    UndefinedOrderStatus : 'Undefined Order Status',
    EstimatedDeliveryTime : 'est delivery time',
    OrderCanceled : 'Order Canceled',
    YourOrderCanceledBy : 'Sorry for inconvenience, your order has been cancelled by the outlet',
    // ---------- Bottom Drawer ----------//
    YourDriver : 'Your Driver : ',
    DeliveryTime : 'Delivery Time : ',
    PaymentMethod : 'Payment Method',
    Cash : 'Cash',
    CancelOrder : 'Cancel Order',
    IfYouWantToCancelThisOrder : `If you want to cancel this order please contact Gamigedara Support`,
    CancelThisOrder : 'Cancel This Order ?',

    //Restaurant List 
    Est : 'Est.',
    Mins : 'mins',
    Eats : 'Food',
    Grocery : 'Grocery',
    Fashion : 'Fashion',
    Doyouwantclearcart : 'Do you want to clear cart or save it for later',
    StartNewOrder : 'Srart New Order',
    Clear : 'Clear',
    UnableToFindStoresNearYou : 'Unable to find stores near you',
    Searchrestaurant : 'Search restaurant...',
    Searchgrocery : 'Search grocery...',
    Searchfashion : 'Search fashion...',
    Within : 'Within',
    Minutes : 'minutes',
    All : 'All',

    //Orders Page
    YouHaveNOrders : 'You Have No Orders',
    YouHaveNoSavedCart : 'You Have No Saved Cart',
    View : 'View',
    Track : 'Track',
    OrderId : 'Order Id',
    OrderDate : 'Order Date',
    OrderStatus : 'Order Status',
    Cart : 'Cart',
    Clearsavedcart : 'Clear saved cart',
    AddThisItemsToCart : 'Add this items to cart ?',
    ClearSavedItems : 'Clear saved items ?',
    IfYouHadAny : 'If you had any issues with this specific order, please contact us',
    Hotline : 'Hotline',
    Whatsapp : 'Whatsapp',

    //*** Order Steps ***//
    Pending : 'Pending',
    Confirmed : 'Confirmed',
    Preparing : 'Preparing',
    Prepared : 'Prepared',
    DriverPicked : 'Driver Picked',
    Delivered : 'Delivered',

    // Order View
    ThanksForOrdering : 'Thanks for ordering, ',
    HereIsYourRecipt : 'Here is your recipt for order id ',
    CardPayment : 'Card Payment',
    CashPayment : 'Cash Payment',
    MerchantName : 'Merchant Name',
    ContactNumber : 'Contact Number',
    RecieverName : 'Receiver Name',

    // Restaurant Info
    RatingsReviews : 'Ratings & Reviews',
    Ratings : 'Ratings'
}